# Generated by Django 5.0.14 on 2026-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcampaign',
            name='whatsapp_phone',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='link_url',
            field=models.CharField(blank=True, help_text='For WhatsApp: phone number (e.g. 2557XXXXXXXX). For Instagram/Facebook: full URL.', max_length=200),
        ),
    ]
