# Generated by Django 5.0.14 on 2026-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MARKETING', 'Marketing'), ('SALES', 'Sales'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
